sudo: required
services:
  - docker

before-install:
  - docker build -t rahulmonish/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=True rahulmonish/react-app npm run test



deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: frontend
  env: Frontend-env
  bucket-name: "elasticbeanstalk-us-east-1-337351555924"
  bucket-path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

